name: Auto Publisher 8am-1pm-daily

on:
  schedule:
   - cron: '1 0 * * *'
jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
    - name: curl
      uses: wei/curl@master
      with:
        args: "-X POST -H 'Authorization: token ${{ secrets.PAGES_ACCESS_TOKEN }}' -H 'Accept: application/vnd.github.ant-man-preview+json' https://api.github.com/repos/technicaloutcast/technicaloutcast.github.io/pages/builds"
